name: Koth
description: King of the Hill plugin.
version: ${project.version}
author: TRSoftware
main: com.trsoftware.koth.Koth
commands:
  koth:
    description: King of the Hill command
    usage: /koth help